### ISSUE TITLE
Archlinux AUR package

### ISSUE THREAD

**Issue by jrch2k10** [cameron314/concurrentqueue#100]
Hi, guys

Any Archlinux user that need to concurrent header for their project can now use AUR directly.

you can find them by maintainer "jrch2k17"(me btw) or by concurrent-queue-git

I made this package for convenience, it just install the header in /usr/include/concurrentqueue/ for those that wanna use this code in several projects and prefer to work with a single copy instead of having 100 versions around

To the team, first thanks for this nice piece so software and second I didn't read about any restriction on packaging for your code so I went and package it(all point directly to this site of course), if for any reason you don't wish to have external packages(in AUR in this case) I have no problem in taking the packages down(and sorry in that case and maybe add a warning in your MD for future cases)

**Comment by cameron314** [comment]
I generally don't do packages because I hate maintaining them (and I don't like most package managers anyway), preferring drop-in headers. But it's nice to have one centralized version, and not have to maintain it, so thanks :-)

There's nothing in the license that says you can't repackage my code. That's totally fine.

P.S. "The team" is just me, lol.

**Comment by jrch2k10** [comment]
great, many thanks and no worries I handle the package  ;)
