### ISSUE TITLE
Missing try_dequeue_from_producer in blocking queue?

### ISSUE THREAD

**Issue by graphicsMan** [cameron314/concurrentqueue#136]
Is there a strong technical reason for leaving out the two dequeue from_producer variants on the blocking queue?  I'm finding myself in a position where I'd like to use one or both of them.  I had a quick look, and it didn't seem too difficult, but the code in general is pretty dense and nontrivial to grok, so I thought I'd ask here before going on an adventure :-)

**Comment by graphicsMan** [comment]
I'm thinking something roughly like this:

`       template<typename U>
	inline bool try_dequeue_from_producer(producer_token_t const& token, U& item)
	{
		if (sema->tryWait()) {
                        // ***  
			if (inner.try_dequeue_from_producer(token, item)) {
				return true;
			}
			sema->signal((LightweightSemaphore::ssize_t)(ssize_t)1);
		}
		return false;
	}
`

Regarding `***`, I'm unsure if it ever makes sense to produce and consume concurrently on the same producer token?  If not, a single `if` makes sense, but if that concurrency can happen, it might make sense to spin a few times before giving up.

Thanks for the nice queues btw.  They're really coming in handy in multiple places for a project I'm working on.

**Comment by cameron314** [comment]
They were left out because there's no "clean" way to implement them. The semaphore maintains a global count of the number items available, but the `_from_producer` methods work with a single sub-queue.

Your implementation should work, but I was really trying to avoid having the semaphore *temporarily* decrement, since:
1) Observers from the outside can see this odd intermediate state
2) The time between the semaphore wait and signal is indeterminate
3) There's significant overhead when the overall queue is not empty, but the producer is (constant wait/signal pairs)

It does make sense to produce and consume on the same producer token concurrently, but not to spin-wait, since only a blocking operation should attempt to spin-wait (otherwise the overhead of just checking if an item is available becomes very large when the queue is empty).

**Comment by cameron314** [comment]
Not going to add them to the queue, sorry.
