### ISSUE TITLE
Support For Move Semantics

### ISSUE THREAD

**Issue by JohnSully** [cameron314/concurrentqueue#139]
This is part feature request, and also a part asking to understand the current API a bit.  Is there a reason it relies so heavily on copies - or did it just work out that way?

**Comment by cameron314** [comment]
Everything is moved if possible.
Where are you seeing copies made? Are your move constructors/assignment operators marked `noexcept`?

**Comment by JohnSully** [comment]
It is a struct with std::functio<void()>() in it.  I'm seeing an error that the copy ctor has been deleted.

My own attempts at custom move ctors were likely foiled by not using noexcept.

**Comment by lalishansh** [comment]
./~vendor/MOODYCAMEL/concurrent_queue.h:2519:93: error: call to implicitly-deleted copy constructor of 'SETU::Event_Base'
                                  MOODYCAMEL_CONSTEXPR_IF (!MOODYCAMEL_NOEXCEPT_CTOR(T, U, new (static_cast<T*>(nullptr)) T(std::forward<U>(element)))) {
-----------------------------------------------------------------------------------------------------------^
./~vendor/MOODYCAMEL/concurrent_queue.h:208:66: note: expanded from macro 'MOODYCAMEL_NOEXCEPT_CTOR'
  #define MOODYCAMEL_NOEXCEPT_CTOR(type, valueType, expr) noexcept(expr)
./~vendor/MOODYCAMEL/concurrent_queue.h:1376:94: note: in instantiation of function template specialization 'moodycamel::ConcurrentQueue<SETU::Event_Base>::ImplicitProducer::enqueue<moodycamel::ConcurrentQueue<SETU::Event_Base>::CannotAlloc, const SETU::Event_Base &>' requested here
                  return producer == nullptr ? false : producer->ConcurrentQueue::ImplicitProducer::template enqueue<canAlloc>(std::forward<U>(element));
./~vendor/MOODYCAMEL/concurrent_queue.h:1063:15: note: in instantiation of function template specialization 'moodycamel::ConcurrentQueue<SETU::Event_Base>::inner_enqueue<moodycamel::ConcurrentQueue<SETU::Event_Base>::CannotAlloc, const SETU::Event_Base &>' requested here
                  else return inner_enqueue<CannotAlloc>(item);
src/Application/EventQueue.cpp:12:18: note: in instantiation of member function 'moodycamel::ConcurrentQueue<SETU::Event_Base>::try_enqueue' requested here
                  return g_queue.try_enqueue(in);
./ENGINE/Base/Event.hpp:81:3: note: copy constructor is implicitly deleted because 'Event_Base' has a user-declared move constructor
                  Event_Base(Event_Base &&oth)
  In file included from src/Application/EventQueue.cpp:7:
  
  [2 more of them]
./~vendor/MOODYCAMEL/concurrent_queue.h:2537:93: error: call to implicitly-deleted copy constructor of 'SETU::Event_Base'
                                  MOODYCAMEL_CONSTEXPR_IF (!MOODYCAMEL_NOEXCEPT_CTOR(T, U, new (static_cast<T*>(nullptr)) T(std::forward<U>(element)))) {
-----------------------------------------------------------------------------------------------------------^
./~vendor/MOODYCAMEL/concurrent_queue.h:2544:47: error: call to implicitly-deleted copy constructor of 'SETU::Event_Base'
                          new ((*this->tailBlock)[currentTailIndex]) T(std::forward<U>(element));
-----------------------------------------------------------------------------------------------------------^


Can't we make these operations non copying?
