### ISSUE TITLE
try_enqueue problem. Slow(eg: every 1ms to consume queue) Consumer or not consumer till queue full

### ISSUE THREAD

**Issue by HuanGong** [cameron314/concurrentqueue#145]
when i use a timer task to consumer the queue,  `try_enqueue` will failed always till queue be consumed or use `enqueue` ;  I wanna queue hold 1w item, but it failed enqueue at 1024, 2048 ...;
in my mind, `try_enque` will failed after all 1w item enqueued, but it seems not. 

here is the code:
```
#include "iostream"
#include <cmath>
#include "concurrentqueue.h"


int main() {
  // one producer, no consumer, cap: 10000
  int size = std::ceil((double(10 * 10000) / 32.0 - 1  + (2  * 1)) * 32);

  std::cout << "1w item with one producer use size:"  << size << std::endl;

  moodycamel::ConcurrentQueue<int> queue(size, 0, 1);

  int try_enqueue_failed_index = 0;

  // try enque a bigger amount of element
  for (int i = 0; i < 100000 ; i++) {

    try_enqueue_failed_index = i;
    bool push_success = queue.try_enqueue(i);

    if (!push_success) {
      std::cout << " try enqueue failed at:" << try_enqueue_failed_index << " queue size approx:" << queue.size_approx() << std::endl;
      push_success = queue.enqueue(i);

      if (!push_success) {
        std::cout << "double failed,  at:" << try_enqueue_failed_index << " approx size:" << queue.size_approx() << std::endl;
      }
    }
  }
  std::cout << "approx size:" << queue.size_approx() << std::endl;
  return 0;
}
```
the output:
```bash
1w item with one producer use size:100032
 try enqueue failed at:1024 queue size approx:1024
 try enqueue failed at:2048 queue size approx:2048
 try enqueue failed at:4096 queue size approx:4096
 try enqueue failed at:8192 queue size approx:8192
 try enqueue failed at:16384 queue size approx:16384
 try enqueue failed at:32768 queue size approx:32768
 try enqueue failed at:65536 queue size approx:65536
approx size:100000
```

**Comment by cameron314** [comment]
First off, your `size` variable can simply be initialized with `100000`, since the 3-argument constructor of the queue already calculates the upper bounds for you.

The reason that `try_enqueue` fails at these boundary points is because, even though there's enough element blocks already reserved, it's not allowed to allocate *any* memory, and there's a few internal indexes that need to be expanded incrementally (in addition to just the space for the elements which is already taken care of).

The initial size of these indexes is controlled by the parameters in the traits. For example:

    struct LargeImplicitIndexTraits : moodycamel::ConcurrentQueueDefaultTraits {
      static const size_t IMPLICIT_INITIAL_INDEX_SIZE = 4096;
    };

and then using `moodycamel::ConcurrentQueue<int, LargeImplicitIndexTraits> queue(100000, 0, 1)` instead yields the following output with your sample code:

    1w item with one producer use size:100032
    approx size:100000
