### ISSUE TITLE
how does consumer retrieve from the queue

### ISSUE THREAD

**Issue by tobyfan1980** [cameron314/concurrentqueue#151]
In the document, the author mentioned that there are multiple sub-queues owned by each producer. But it doesn't detail how consumer get an item.  Since there are multiple sub-queues, does a consumer go over them in certain order to find an un-empty one?

Our experiment shows a weird behavior.  First, we have one thread to enqueue a number of items. Then, the same thread retrieve items, which will be enqueued back by some other threads.   What we observe is that one item has 90% of chance to be retrieved. 

Can you explain what happened?

**Comment by cameron314** [comment]
Since there are multiple sub-queues, the consumer iterates over them in arbitrary order looking for an element to dequeue. When using consumer tokens, the same sub-queue is used multiple times in a row if possible.

What do you mean by "90% chance to be retrieved"? All items will get dequeued eventually.

**Comment by tobyfan1980** [comment]
@cameron314 can you elaborate "arbitrary order", any specific algorithm behind it?

Suppose I put 3 items, A, B, C in the queue.  I have a thread call wait_queue() to get one out and some other thread enqueue it back later. Then do it over again. What I observed is that 90% of time wait_queue() get A.

**Comment by cameron314** [comment]
There's a linked list of producers/sub-queues that is traversed in order; as soon as a non-empty one is found, an element is dequeued from it. (With consumer tokens there's also an added stickiness to the last used sub-queue.)

In your example, there's a race between the thread putting A back and the consumer thread seeing its presence, which could explain the 90%.

**Comment by tobyfan1980** [comment]
Is traversal the linked list thread safe? If there are multiple consumers dequeueing at the same time, how to ensure they will get different items?

Is the linked list circular? If not, every dequeue will traverse from head. As a result, if item A is always put back to the same sub-queue which is at the beginning of the linked list, it explains why A has more chance to get retrieved from queue.

**Comment by cameron314** [comment]
Yes, the queue internals are thread-safe, otherwise it wouldn't be very useful as a concurrent queue :-)

The dequeue operation is essentially atomic, so if one consumer dequeues an element, the other consumer will necessarily get a different one.

The linked list is not circular; indeed, every dequeue traverses from the head, which is mostly why using a  consumer token makes dequeueing more efficient.

**Comment by tobyfan1980** [comment]
To my understand, if a producer uses a token to enqueue, the consumer who uses the same token to dequeue will directly go to the same sub-queue to fetch instead of traverse the linked list.  If I am right, what if the queue corresponding to the token is empty,  will it go to the next sub-queue in the linked list to try, or just wait on this one?

**Comment by cameron314** [comment]
Producer tokens and consumer tokens are two different token types. When dequeueing using a consumer token, a heuristic is used to determine if the previous sub-queue should be  consumed from again or if the consumer should advance to the next sub-queue. If the selected sub-queue is empty, the consumer passes on to the next one. It will attempt to dequeue from every sub-queue before returning failure (empty case).

**Comment by tobyfan1980** [comment]
So each token is mapped to a sub-queue the last time the token is used?  How to determine if advance to the next sub-queue based on the token? Thanks.

**Comment by cameron314** [comment]
The token simply stores some state. Each time you dequeue using a token, the sub-queue that was consumed from is noted in the token for the next time. This information is used to help reduce the number of sub-queues that need to be checked, and increase throughput by dividing the sub-queues amongst the different consumers roughly evenly.

If a sub-queue is empty, the consumer will try the next one (or all of them in the worst case). It also advances every so many elements (256, I believe).

You cannot know in advance which sub-queue will be checked first because the state of the queue is constantly changing thanks to the other threads in the system.

The initial state of the token is not random, but from the user's perspective it may as well be since it's arbitrary which sub-queue will get checked first (depends on all this other state which is changing concurrently).

**Comment by NikitaMishin** [comment]
Regarding explicit producer tokens, do I need explicit sync if I push by one token from different threads at the same time? Or does it thread-safe since you have mentioned that internally all queues are threadsafe?

**Comment by NikitaMishin** [comment]
Find similar questions, ok.
Then my question is following: do the usage of explicit synchronization for producers noticeably impact on performance ?

**Comment by cameron314** [comment]
I'm not sure I understand your question. Using producer tokens does (slightly) improve performance.

**Comment by NikitaMishin** [comment]
Sorry, was in a rush. 

Correct question: what do you mean by " producer  token not thread-safe"? I thought if subqueues  are thread-safe itself then  different threads can push by one explicit token without any synchronization.

**Comment by cameron314** [comment]
The sub-queues are thread-safe to dequeue from, but not to enqueue to. The tokens are designed to speed up access to the queue from a single agent, and are not thread-safe themselves either, though you can pass them between threads as long as you're careful to synchronize access (meaning, don't use the same token from two threads concurrently).

**Comment by NikitaMishin** [comment]
got it, thanks!!!
