### ISSUE TITLE
Can i fix the buffer size?

### ISSUE THREAD

**Issue by yzz-ihep** [cameron314/concurrentqueue#175]
I want to use the queue as an asynchronous buffer.
In order to prevent the queue from expanding indefinitely, how do I fix the buffer size?

**Comment by cameron314** [comment]
You can pass a size in the constructor and use the try_enqueue methods. This limits the amount of memory the queue takes, but  does not impose a specific limit on the number of elements, since this depends on how elements are queued across threads; internally, the queue is more complex than a ring buffer.

**Comment by cameron314** [comment]
If you need a fixed number of elements, consider using a thread-safe ring buffer instead.

**Comment by yzz-ihep** [comment]
> If you need a fixed number of elements, consider using a thread-safe ring buffer instead.

You are right!Thanks!
