### ISSUE TITLE
blockingconcurrentqueue capacity ignored

### ISSUE THREAD

**Issue by pfeatherstone** [cameron314/concurrentqueue#189]
In the constructor for blockingconcurrentqueue, "capacity" seems to be ignored. For example if I set the capacity to 10, the "enqueue" method will not block after 10 enqueues...
Maybe this is expected behaviour but then capacity should be refactored to something else. To me, it means maximum size of queue above which all enqueue calls block, unless dequeue is called.

**Comment by cameron314** [comment]
This keeps coming up. The capacity is a minimum, not a maximum.

For simpler data structures their capacity is a fixed bound, but this queue is structured as a set of sub-queues internally, so there is no single array of elements. Instead, sub-queues manage blocks of element. The capacity just controls how many blocks are allocated up front; but since block sizes must be a power of two, and not all sub-queues release freed blocks back to the shared pool, the size (and producer count) passed to the constructor is used to establish a minimum bound.

**Comment by pfeatherstone** [comment]
@cameron314 Is it possible to have 1 subqueue and set an upper bound on its size?

**Comment by pfeatherstone** [comment]
@cameron314 Or if there is no work-around, would you recommend using another MPMC queue that supports maxcapacity? (this is not a dig, just seeking advice)

**Comment by cameron314** [comment]
There's one sub-queue per producer, so if you only have one producer you could control the bound more exactly (this is why the constructor also accepts the number of producers).

The block size is configurable through the traits.

I'm not familiar with the internals of other queues, but anything based on a ring buffer should give you the option for a fixed capacity (though it's likely to be a power of two there as well).

**Comment by cameron314** [comment]
You might also be interested in the `MAX_SUBQUEUE_SIZE` trait that applies exactly to all sub-queues.

**Comment by cameron314** [comment]
Correct, that is not possible with this implementation. You could wrap all accesses with semaphore, however, if you wanted to implement this yourself. But there would be added overhead. (Also keep in mind the queue is eventually consistent, so you'd need a loop around try_enqueue even if your semaphore tells you there's guaranteed to be a slot available.)

**Comment by h-2** [comment]
Thank you for the quick reply! I will look for a different implementation for now.
