### ISSUE TITLE
Preallocate with byte× buffers

### ISSUE THREAD

**Issue by PhilippPaetzold** [cameron314/concurrentqueue#191]
Hello,
I want to use the blocking queue for storing camera frames each an array of byte[2048x64x4]with a high frequency of 1250 fps  in an acquisition thread (producer) and process them in another thread (consumer). Is it possible to preallocate let's say 3 seconds that is 3750 buffers in the queue and reuse those continously? I can clearly not allocate memory for each frame received on the fly, so I would need some kind of memory pooling. Is this possible with the queue here. It would be great, if somebody could give me some hints on this.

Thank you
Philipp

**Comment by cameron314** [comment]
That's almost 2 GB for 3 seconds. I would not use the queue to store the buffers, since it expects to be able to allocate blocks of multiple elements, and it would be forced to copy the contents on enqueue/dequeue.

You could use the queue to pass pointers to pre-allocated buffers between the producer and consumer. This is quite efficient but places the burden on you to manage the buffer reuse safely. For this, you could use another queue in the opposite direction to pass pointers to used (processed) buffers back to the capture thread to write to.

Finally, if your use case is single-producer single-consumer (SPSC), use my ReaderWriterQueue instead.

**Comment by PhilippPaetzold** [comment]
Hi Cameron,

thank you for the quick reply and the good ideas!

> That's almost 2 GB for 3 seconds. I would not use the queue to store the buffers, since it expects to be able to allocate blocks of multiple elements, and it would be forced to copy the contents on enqueue/dequeue.
Ok, that sounds good to me.

> You could use the queue to pass pointers to pre-allocated buffers between the producer and consumer. This is quite efficient but places the burden on you to manage the buffer reuse safely. For this, you could use another queue in the opposite direction to pass pointers to used (processed) buffers back to the capture thread to write to.

> Finally, if your use case is single-producer single-consumer (SPSC), use my ReaderWriterQueue instead.

Ok, assuming I use the ReaderWriterQueue, I would hide the fact of the two queues in a simple class like below:

```cpp
#pragma once

#include "atomicops.h"
#include "readerwriterqueue.h"
#include <vector>
#include <memory>

class ReaderWriterBufferQueue
{
    public:
        enum class byte : unsigned char {}; 
        using Buffer = std::unique_ptr<byte[]>;

        ReaderWriterBufferQueue() = default;
        virtual ~ReaderWriterBufferQueue() {}

        void initialize (int capacity, int singleBufferSize)
        {
            for (int idx=0; idx < capacity; ++idx)
            {
               auto buffer = std::make_unique<byte[]>(capacity * singleBufferSize);
               _freeBuffers.enqueue (std::move (buffer));
            }

            _singleBufferSize = singleBufferSize;
        }

        // used by the producer thread (the one that gets camera-images)
        bool writeBuffer (const byte* sourceBuffer)
        {
            Buffer freeBuffer;
            bool isAvailable = _freeBuffers.try_dequeue (freeBuffer);
            if (!isAvailable)
            {
                //TODO: handle free buffer is empty error
                return false;
            }

            memcpy_s (freeBuffer.get(), _singleBufferSize, sourceBuffer, _singleBufferSize);
            return  _usedBuffers.enqueue (std::move(freeBuffer));

            return true;
        }

        // used by the consumer thread (the one that reads and processes the camera-images
        // in order, fifo-style)
        bool readBuffer (const byte* destinationBuffer)
        {
            Buffer usedBuffer;
            bool isAvailable = _usedBuffers.try_dequeue (usedBuffer);
            if (!isAvailable)
            {
                // no new buffer available...
                return false;
            }

            memcpy_s ((void*)destinationBuffer, _singleBufferSize, usedBuffer.get(), _singleBufferSize);
            _freeBuffers.enqueue (std::move (usedBuffer));

            return true;
        }        

    private:
        moodycamel::ReaderWriterQueue<Buffer> _usedBuffers;
        moodycamel::ReaderWriterQueue<Buffer> _freeBuffers;
        int _singleBufferSize;
};
```

Did I get your idea right and do you see any general problems with the code aboce? I have to admit that I do not have much experience with the move-semantics, so I hope the implementation is ok.

I also have one question regarding "BlockingConcurrentQueue" vs. "ReaderWriterQueue". In the last one my image-processing-thread (consumer) needs to poll the queue until data becomes available. When I use the blocking queue, I assume that the consumer gets notified whenever something becomes available in the queue. Does this mean the blocking version will need less CPU-time than the polling version? 

Thanks for all the help so far and I hope you are all well
Philipp

**Comment by cameron314** [comment]
At a glance, your code seems reasonable, but I would pass the unique_ptrs directly instead of copying into/out of them (i.e. `writeBuffer` would accept a `Buffer` and `readBuffer` would return a `Buffer`).

`ReaderWriterQueue` is SPSC. `ConcurrentQueue` is MPMC. They both have blocking analogues (`BlockingReaderWriterQueue` and `BlockingConcurrentQueue`). Yes, if you're going to be polling in a busy-wait loop, using the blocking versions instead is more efficient.
