### ISSUE TITLE
`try_equeue` failed even all items are consumed

### ISSUE THREAD

**Issue by dkw72n** [cameron314/concurrentqueue#193]
```c
#include <thread>
#include <cassert>
#include "concurrentqueue.h"
#include <atomic>
int main(int c, char** v){
  int total_producers = atoi(v[1]);
  int tasks_per_producer = 100;
  moodycamel::ConcurrentQueue<int> q;
  int total_tasks = total_producers * tasks_per_producer;
  std::atomic<int> produced(0), consumed(0);
  auto producer = [&](){
      for (int i = 0; i != tasks_per_producer; ++i) {
          while(!q.try_enqueue(i))
            std::this_thread::yield();
          ++produced;
          printf("%d/%d\n", consumed.load(), produced.load());
      }
  };
  for(int i = 0; i < total_producers; ++i){
    std::thread t(producer);
    t.detach();
  }
  for (int i = 0; i != total_tasks; ++i) {
    int task;
    while(!q.try_dequeue(task))
      std::this_thread::yield();
    ++consumed;
    printf("%d/%d\n", consumed.load(), produced.load());
  }
  return 0;
```
The code above might hang forever, the larger `total_producers` is, the more likely it hangs.
On my computer, it's about 20 to make a 100% hang.

output is like
```
$ ./a.out 20
...
1334/1336
1335/1336
1336/1336
```
and then it hangs

The `printf`s suggest that all produced object are consumed.

environment:
```
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
CFLAGS=-lpthread -O0 -g3
Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
```

also reproduced on windows vs2017

**Comment by cameron314** [comment]
The queue is not a simple ring-buffer. Just because the queue is "empty" does not mean that the internal data structures are in a state that can accept more items without allocating memory.

First, this example code is making use of implicit producers (no tokens). Each implicit producer takes up a slot in a hash table, which can fill up (the traits control its initial size, which is 32, but it tries to resize at 16). Use custom traits if you want to control the initial size.

Second, when even a single item is queued, a "block" of elements is taken from the internal pool of free blocks and is assigned to the producer for its exclusive use. Implicit producers do recycle blocks back to the main pool, but hold on to at least one block, and require a second block before reusing or freeing the first. Eventually the pool of free blocks will be exhausted.

If you want `try_enqueue` to always succeed for a given workload, you'll need to use the proper traits and pass the expected max number of elements and producers to the queue's constructor.

**Comment by dkw72n** [comment]
Thank you for quick and insightful replying. It helps me a lot to understand the internal of the queue.

I'm trying to put a cap on the memory footprint. The constructor `ConcurrentQueue(size_t minCapacity, size_t maxExplicitProducers, size_t maxImplicitProducers)` does exactly what I want. 

Since this is not an issue, I'm closing it now.
