### ISSUE TITLE
TSAN data race in bulk interfaces

### ISSUE THREAD

**Issue by graphicsMan** [cameron314/concurrentqueue#196]
I have a case where I have one central ConcurrentQueue, and I have thread-local Producer and Consumer tokens.  I'm using the enqueue_bulk and try_dequeue_bulk interfaces.

TSAN is concerned about data races with writes occurring at concurrentqueue.h:2026 and concurrentqueue.h:2027.  Unfortunately, TSAN isn't helping me out with callstack(s) for the readers.  Is this something you might already be familiar with?  

I see that TSAN failures in the face of lock-free programming have been previously mentioned in #49, but it wasn't immediately clear to me that this is the same issue.  If you are pretty certain it is, I'll look into annotating some code.  If it is likely to be a new issue, I can work to make a minimalish repro case.

**Comment by cameron314** [comment]
It should be benign since the block index (which is what is being updated) is owned by that producer instance and is therefore only updated on that thread. The consumers read from it but they acquire the tail index first, which is released at the end of the enqueue operation, so memory synchronization here is guaranteed.

**Comment by cameron314** [comment]
This may be the same as #146?

**Comment by graphicsMan** [comment]
It doesn't look quite the same, though I'm not quite sure how much the code has changed in the last year+.  I figured out how to get TSAN to give the read stack.  The read is happening at concurrentqueue.h:2235.

Is this maybe due to reuse of blocks from the block pool?  E.g. a block is dequeued from and exhausted, it goes back in the pool, and next enqueue the block is part of the new tail? 

If you're confident this is benign, I'll figure out how to annotate my use of the queue for TSAN.

**Comment by cameron314** [comment]
That's weird, the read is from a block, while the write is to a block index (separate data structure). Honestly it's really hard to tell, because TSAN isn't the best for giving context. You could try to strip things down and reproduce with a smaller example, but I suspect you'll find another false positive.

Explicit producers don't share blocks, they hoard all the ones they acquire for later reuse, so they never go back to the shared pool.

I'm sorry the queue is causing issues with your sanitizer use. I looked into annotating it once and it seemed like it would require too many annotations to be useful. However, TSAN has undoubtedly evolved since then. Perhaps there's a way to ignore by filename?

**Comment by graphicsMan** [comment]
I have a fix in mind.  It operates on the function level, which is less
good from a sanitizer validation standpoint, but much simpler to annotate,
and where we are not really concerned about tsan validation in this
library, it should be low developer overhead.

I'll try to send a PR within a few days.  I have to get permission from my
employer to contribute first.
