### ISSUE TITLE
BlockingConcurrentQueue does not compile with exceptions disabled (Clang)

### ISSUE THREAD

**Issue by jlaumon** [cameron314/concurrentqueue#20]
Hey

I'm trying to compile BlockingConcurrentQueue with exceptions disabled with Clang. 

It looks like the ifdefs detect properly that the exceptions are disabled (I get no errors coming from MOODYCAMEL_TRY/CATCH), but the two throw std::bad_alloc() in BlockingConcurrentQueue constructors are not protected by any macros and trigger an error like:

`error : cannot use 'throw' with exceptions disabled`

Do you have a point of view on the matter?

**Comment by cameron314** [comment]
Oops. That's a plain-old-bug in my code, thanks for reporting it!

I suppose I should try to eliminate the heap allocation entirely, but it's extremely convenient because it allows the OS-specific semaphore implementations to be both non-copyable and non-moveable while still allowing the queue itself to be moveable.

I think the best option is simply not to throw when exceptions are disabled, and to allow the null reference to simply abort the program the next time the queue is accessed in that case.

**Comment by cameron314** [comment]
Should be fixed now!

**Comment by jlaumon** [comment]
Great! Thanks again.
