### ISSUE TITLE
Create concurrent topic?

### ISSUE THREAD

**Issue by raul-guerrero** [cameron314/concurrentqueue#205]
Hi,

Your work seems pretty amazing! congrats on creating concurrent queue, it has been really helpful for learning lock free concurrency.

Have you considered creating a "topic" version of your queues? where you have your multiple consumers receiving the same message published by the publisher at the same time?

cheers!

Raul

**Comment by cameron314** [comment]
Thanks :-)
Yeah, I purposefully tried to stay away from the whole pub-sub/broadcasting thing and concentrate on a "simple" data structure rather than create a more complex component.

**Comment by williamleong** [comment]
I've used the queue as the basis for a pub-sub message bus and it's proven to be quite effective and reliable. If you want to create topics dynamically, you'll have to roll your own code to maintain the list of queues in a lock-free way.

Unfortunately, I could not use the blocking version of the queue as the the spin-lock kills the CPU when you have many copies of the queue running. Instead, I poll the queue with exponential back off and it's working well so far.

**Comment by raul-guerrero** [comment]
@williamleong sounds nice, do you have some code you can share on that?
Thanks!

**Comment by williamleong** [comment]
@raul-guerrero Apologies, not at the moment, but if I ever get around to decoupling and tidying up the code I'll give you a ping.

The idea is to have a message bus class that loads a static list of topic classes during initialization. A lock free list should do the trick for a dynamic implementation, I used a more complex (but now I think unnecessary) lock free map implementation using shared pointers and compare-and-swap.

Each topic class exposes a publish function that adds items to its publish queue. Another function also allows the dynamic registration of subscribers. I use a mutex to protect the list of subscribers, but this should really be a lock free list. There is also a thread that periodically polls the publish queue to dequeue items and enqueues them into subscriber classes.

Subscriber classes contain a subscriber queue, a polling thread, and a callback function pointer. The thread periodically polls the subscriber queue and invokes the callback function pointer.

I rolled this out because other message bus solutions are too complex, slow to setup and teardown for use in test cases when I require multiple copies of the message bus, or require serialization which is unnecessary for my use case.

**Comment by cameron314** [comment]
I could probably parameterize the spin-lock iterations if you need.

**Comment by williamleong** [comment]
@cameron314 I would definitely be on board to try it out. I switched over in sometime in May 2018 due to the profiler showing the spin-locks using up all the CPU cores (I'm running somewhere between dozens to hundreds of the queues), so I don't know if the system semaphore is something newer that could have fixed the problem.

**Comment by cameron314** [comment]
There's always been a system semaphore under the spinning. The cost of waiting on it when an element is a few cycles away from arriving exceeds the cost of spinning in typical cases. So when waiting, first it spins a few thousand times, then it goes to sleep on the semaphore. It your case it sounds like it would be advantageous for the threads to sleep right away.

**Comment by williamleong** [comment]
Yep, that makes sense, appreciate your explaining the details.
