### ISSUE TITLE
I can't understand how this queue ensure ordering between multiple producer...

### ISSUE THREAD

**Issue by SungJJinKang** [cameron314/concurrentqueue#262]
I read all post in your blog. 
I can't understand how this queue ensure ordering between multiple producer.

For example.
First producer enqueue item1 at time 1
First producer enqueue item2 at time 5
Second producer enqueue item3 at time 10
First producer enqueue item4 at time 15
Second producer enqueue item5 at time 20
Second producer enqueue item6 at time 25

all enqueue is ensured being enqueued sequentially

fence

Consumer pull items from queue.
Items should be return in order put into queue.

But from what i understand, items will be returns like this. 
item 1 -> item 3 -> item 2 -> item 5 -> item 4 -> item 6.
Because it pull item from producer having the most element.
Am I understanding wrong????

does it ensure item1 -> item2 -> item3 -> item4 -> item5 -> item6??

**Comment by cameron314** [comment]
There is no defined order in which elements enqueued by different producers will be dequeued.

In your example, item1 is guaranteed to come out before item2, which in turn is guaranteed to come out before item4, because they were all enqueued onto the same sub-queue.

Similarly, item3, item5, and item6 will come out in that order relative to each other.

But, the *interleaving* between the two streams of elements from the different producers is undefined. Item3 may come out first.

**Comment by SungJJinKang** [comment]
i understand.. thanks for your reply
