### ISSUE TITLE
Why define threadId()?

### ISSUE THREAD

**Issue by Cthutu** [cameron314/concurrentqueue#43]
Hi,

Why do you defined the function in moodycamel::details called threadId?  Can the same be accomplished by using the C++11 std::this_thread::get_id()?

Maybe I am misunderstanding the use.

Thanks.

**Comment by cameron314** [comment]
Sorry for the delay, I accidentally broke all incoming traffic (including emails, like those from GitHub) to my server :-{

There's two reasons. First, `std::thread::this_thread::get_id()` is very slow on certain key platforms, like Windows (orders of magnitude slower than calling `GetCurrentThreadId()`). Second, the type of the object returned is implementation defined. I need a thread ID that I can use inside a special-purpose lock-free hash internally, and for that I need some sort of numeric/pointer type with a defined maximum size.

I only use `std::thread_id` on iOS because there's no better way to get a thread ID, and even then it's reinterpreted as a numeric type (this relies on platform-specific implementation details, but is better than not having support for iOS at all, and these details are at least unlikely to change).

**Comment by Cthutu** [comment]
Thanks for the reply.  I was just curious.

**Comment by cameron314** [comment]
No problem :-)
