### ISSUE TITLE
bluk_enqueue with move_iterator seems to stil copy when the copy constructor is not deleted

### ISSUE THREAD

**Issue by koraa** [cameron314/concurrentqueue#45]
Hi, as stated above, I think I found a case in my program where I am trying to move elements from a vector into the queue using batch_enqueue, but the elements are still copied.

I looked at the tests and it seems elements are moved when copying is deleted; here is a demo: https://github.com/SoftwearDevelopment/concurrentqueue/commit/86965b2a9795aa7f41152aef7d57e3c99663da52

**Comment by cameron314** [comment]
Your changes to my unit tests pass for me, once I fix the bug where `copied` was never initialized.

Copying elements during a bulk enqueue is normal. It's part of the [exception safety guarantee](https://github.com/cameron314/concurrentqueue#exception-safety). If there's an exception during a bulk enqueue, the bulk enqueue as a whole is canceled -- and since normally you don't want to lose the objects that had already been moved up to that failure point, they are copied instead of moved. `std::vector` has similar semantics on a resize, for example.

However, elements will be moved instead of copied if the queue can detect that your move constructor can never throw an exception -- you simply need to annotate your move constructor with `noexcept` (or `throw()` if on VS2013).

**Comment by koraa** [comment]
Sorry for the bug, I probably should have gone to bed around five hours earlier yesterday.
 
Thanks for the clarification, my tests work now!

**Comment by cameron314** [comment]
No worries, glad it turned out to be a false alarm :-)
