### ISSUE TITLE
The maximum size of the queue is 1024？

### ISSUE THREAD

**Issue by chenspnjupt** [cameron314/concurrentqueue#50]
I‘ve wotten test code following:
int main(int argc, char** argv)
{
    ConcurrentQueue<int> queue(10000000);
    cout << queue.size_approx() << endl;
    for(int i = 0; i < 40000; i++)
    {   
        if(!queue.try_enqueue(i))
            cout << i << " queue is full" << endl;
    }   
}

but the result is:
[signal@keyuanfenxi02 test]$ ./test  | more
0
1024 queue is full
1025 queue is full
1026 queue is full
1027 queue is full
1028 queue is full
1029 queue is full

How can I add more element into the queue？

**Comment by chenspnjupt** [comment]
I have solved it by change the BLOCK_SIZE, tks

**Comment by cameron314** [comment]
Interesting! You're actually hitting the limit on the `IMPLICIT_INITIAL_INDEX_SIZE`. By default, this is 32, and so is the `BLOCK_SIZE`. Since no one is dequeueing from the queue, the index fills up (one entry is taken for each block inserted) until it's completely full. This happens after 32 blocks, which means 32*32 elements -- this is where the 1024 limit is coming from. `try_enqueue` is not allowed to allocate memory, so it fails when the block index is full.

I admit this is not something I had thought about when designing the queue. It's a little unfortunate. Sorry!

You'll need to change `IMPLICIT_INITIAL_INDEX_SIZE` (or `EXPLICIT_INITIAL_INDEX_SIZE` if using explicit tokens) to something at least as large as `10000000/BLOCK_SIZE` if you want to enqueue without ever allocating new memory. A good balance would probably be blocks of around 1024-4096 and a corresponding index size of 10K-2K.

**Comment by chenspnjupt** [comment]
Tks for your reply. I got it . Tks versy much!
