### ISSUE TITLE
CAS Memory Order in Semaphore fails compile check GCC4.8 

### ISSUE THREAD

**Issue by BlamKiwi** [cameron314/concurrentqueue#51]
In blockingconcurrentqueue.h:291 you appear to have your memory barriers slightly wrong in the spin part of the semaphore. You have relaxed on your success barrier but acquire on your failure barrier causing the code to not pass sanity checks during compilation on GCC4.8 (and I assume later). This is not valid C++11 as your success barrier should be at least as strong as the failure barrier. 

`if (oldCount < 0 && m_count.compare_exchange_strong(oldCount, oldCount + 1, std::memory_order_relaxed, std::memory_order_acquire))`

The success barrier should be `std::memory_order_acquire` as well if I'm understanding the purpose of the loop correctly.

**Comment by cameron314** [comment]
Ah. Yes.  I only need acquire on failure, but I forgot C++11 doesn't support that. I'll change it, thanks!

In case you're curious, at that point in the function, `m_count` had been decremented ahead of time, but the wait on the semaphore timed out, so the CAS attempts to restore the count to what it was so that it can return failure. When the CAS succeeds, there's no memory ordering needed because there is no exchange of data with another thread -- the count was merely restored to what it was at previously. When the CAS fails, though, we want an acquire on the subsequent read of the count for the next part of the loop.
