### ISSUE TITLE
Blocking Enqueue Methods (Feature Request)

### ISSUE THREAD

**Issue by BlamKiwi** [cameron314/concurrentqueue#53]
Your blocking Concurrent Queue has wait and wait_for methods defined for dequeue. If there were analogous methods for enqueue in conditions where we don't want to allocate memory, that would be super useful for creating pipeline style code.

**Comment by cameron314** [comment]
I agree. Not likely to happen in the near future, though. Since the queue is really a collection of independent sub-queues, based on blocks of elements and variable-sized indices, it's more tricky than just keeping a semaphore on "the number of free slots" since there isn't really such a thing.

I think this would make more sense if I moved to a different design altogether.

**Comment by BlamKiwi** [comment]
I did simulate it using spinning. Perhaps all you need to do is use a condition variable instead of your full Semaphore that's just signalled on a dequeue?

**Comment by cameron314** [comment]
The semaphore is very efficient. Implementing a similarly efficient condition variable would be a bit of a challenge.

Anyway, it still wouldn't be enough, because the condition can't easily be checked in advance :-) The present try-then-fail semantics give a lot more flexibility to the algorithm implementations than a reserve-then-execute model, which would be ideal for this feature.

Although I suppose it could all be simulated -- use a semaphore or two to simulate a poor man's condition variable, then try-fail and go back to waiting on failure. Non-trivial enough that it's still a ways away on the horizon, I'm afraid.

**Comment by cameron314** [comment]
I'm afraid I'm no longer adding new features to the queue, so I'm going to close this issue.
