### ISSUE TITLE
it seems that no need to include boost and tbb headers

### ISSUE THREAD

**Issue by baiwfg2** [cameron314/concurrentqueue#56]
Including these headers makes the source size bigger, I think.

**Comment by baiwfg2** [comment]
the dependencies should be left users to obtain, not the source code author, although it makes building process more convenient

**Comment by cameron314** [comment]
I think you're right in theory, but it's just too convenient. And not just for others, but for me! I don't have boost or TBB installed system-wide, and the versions I've committed are stripped-down and modified to compile directly (TBB is not made to link statically, for example, but I wanted the benchmarks to be a single binary insofar as possible). Also, keep in mind that it's already happened that a newer version of boost broke the benchmarks -- so there's versioning concerns too :-)

Since there's no universal package management system for C++ yet, I decided to embed all dependencies directly.
