### ISSUE TITLE
Single producer, multi-consumer audio processing

### ISSUE THREAD

**Issue by robclouth** [cameron314/concurrentqueue#59]
I'm trying to use this (amazing) project for multi-threading some audio processing algorithm. It's a synthesiser with 50 separate voices (notes) that can be played at the same time.

I set up the consumer threads like so:

```
processQueue = moodycamel::BlockingConcurrentQueue<VoiceProcessTask>(numVoices);
numThreads = SystemStats::getNumCpus();

for (int i = 0; i < numThreads - 1; i++) {
            processThreads.push_back(thread([&, i]() {
                int maxTasks = numVoices / numThreads;
                vector<VoiceProcessTask> tasks(maxTasks);
                VoiceProcessTask task;
                moodycamel::ConsumerToken token(processQueue);

                while (true) {
                    int count = processQueue.wait_dequeue_bulk(token, &tasks[0], maxTasks);

                    for (int i = 0; i < count; ++i) tasks[i].process();

                    voicesRemaining.fetch_add(-count, std::memory_order_release);
                }
            }));
        }
```

The maxTasks is an attempt to spread the voices over each thread, because I assume that otherwise the first thread will snatch all the Tasks.

Then everytime the sound device needs a new block of audio, this is called:

```
voicesRemaining = voices.size();
        for (int i = 0; i < voices.size(); ++i) {
            processQueue.enqueue(
                VoiceProcessTask(voices.getUnchecked(i), &buffer, startSample, numSamples));
        }

        int count;
        while (voicesRemaining.load(std::memory_order_acquire) > 0) {
            int count = processQueue.try_dequeue_bulk(&remainingTaskList[0], numVoices / numThreads);
            voicesRemaining.fetch_add(-count, std::memory_order_release);
            for (int i = 0; i != count; ++i) {
                remainingTaskList[i].process();
            }
        }
```

However, the audio crackles if I use the multi-threading. I checked that voicesRemaining is zero at the end of each block and it is, so the processing is finishing it seems. Am I doing something silly? The crackles suggest that the voices are being processed fast enough, leading to buffer overruns. 

Also using the xcode profiler it seems that overall, the multi-threaded code uses more cpu time. Any tips here?

Thanks

**Comment by cameron314** [comment]
Hmm, I'm not sure it's a good idea to dispatch so few tasks across threads. Roughly how long does it take to process a single voice task? There's a non-negligible cost to schlepping data around between threads, and the latency can vary significantly. Any multithreaded code will always be less efficient than the equivalent single-threaded code (the only advantage is that it can execute across multiple cores in parallel, bringing down the wall clock time even if the CPU time is technically higher).

I don't know much about audio processing, but I don't follow your analysis of what the crackles mean. I would have assumed that it meant the audio data wasn't being generated fast enough to keep up with the demands of the hardware. What buffer could be overrun?

It's probably a better idea to do the audio processing outside of the audio callback where possible, in order to have the data ready to go when the driver asks for it. I know this can be tricky because it can add unwanted latency to your pipeline.
