### ISSUE TITLE
Need to understand ConcurrentQueue 

### ISSUE THREAD

**Issue by necromancersecret** [cameron314/concurrentqueue#60]
Hello
I am looking for some faster queuing library and then when i saw the benchmark results of ConcurrentQueue, it's just awesome.. 

I am learning this, i need to understand few things whats this ConcurrentQueueDefaultTraits? 
I mean under which circumstances I should use this 
And I am going to produce from multiple threads and going to consume from respective consumer threads Do i need to just create one instance of something like 

ConcurrentQueue<customeObject, Traits> q; or each thread have 
ConcurrentQueue<customeObject, Traits> q;

**Comment by necromancersecret** [comment]
Hello any help ?

**Comment by cameron314** [comment]
I've been busy, sorry. I don't have much spare time, and this issue was only opened yesterday, on the weekend to boot. Keep your shirt on ;-) If you want a more immediate response for general questions, your best bet is probably Stack Overflow.

You don't have to worry about `ConcurrentQueueDefaultTraits` most of the time. It provides default values for various configurable parts of the queue that you don't need to tweak right away. You could use it to fine-tune performance for your particular usage of the queue after having integrated it into your application, if required. For example, it provides the `malloc` and `free` functions that the queue uses to allocate memory; if desired, you could replace those with your own custom allocation functions. (The unit tests do exactly this in order to check that there's exactly one `free` for every `malloc`.)

The simplest design is to use a single queue shared between all threads. But this is often not the most efficient way. Depending on the constraints of your application, having one queue per producer/consumer pair (a single-producer, single consumer (SPSC) queue instead of this MPMC queue) is generally more efficient (because it minimizes the amount of data that is shared between threads -- ideally you want to share as little as possible with as few other threads as possible in order to reduce the memory bandwidth required at the hardware level, which is almost always the bottleneck).

**Comment by necromancersecret** [comment]
Dear cameron 
Thanks
So I have 4 Producer Threads and 4 Consumer Threads. 
In each Producer thread  I am creating Queue like ConcurrentQueue<Object, MallocTrackingTraits> *m_Queue;  and correspondingly saving corresponding Queue Pointer in respective Consumer Threads. ? 
I am not using any token ? Whats the reference of token ?

Neo

**Comment by cameron314** [comment]
If I understand correctly, you have a set producer/consumer pairs, with one queue each.

Allocating the queue on the producer thread and passing a pointer to it to the consumer thread is perfectly valid, as long as the queue exists before the consumer thread starts using it (either because the consumer thread was spawned after the queue was created, or via explicit synchronization between the two threads). Similarly, the queue must not be destroyed until after both threads have finished using it.

Tokens are an optional feature purely for increasing throughput (performance). Each producer can create a producer token, and pass that to the queue when enqueueing Similarly, each consumer can create a consumer token, and pass that to the queue when dequeueing. There's some examples in the README and the samples.

If you really are using a single producer and single consumer thread with each queue object, this queue implementation (which supports arbitrary numbers of accessing threads) is not as efficient as using one built specifically for the single-producer, single-consumer (SPSC) scenario. I have a very efficient and slightly simpler [SPSC queue implementation here](https://github.com/cameron314/readerwriterqueue).

**Comment by necromancersecret** [comment]
Thanks a ton cameron
Initially all the producer threads gets created and in that I am creating respective queue handles.
After that I create the consumer threads and save the queue pointers respectively in consumer threads.. 
Its a thread pool , so it does not have any exit conditions both in producer and consumer threads.. 
Exit conditions in threads , are only for very fatal exceptions.
Thanks for referring to new queue , which one i should use i should use spscqueue.h or readerwriterqueue.h or ProducerConsumerQueue.h

**Comment by necromancersecret** [comment]
I am little confused like whats MAX BLOCK Size, does it mean that no of Nodes of each type <T>

**Comment by cameron314** [comment]
readerwriterqueue.h contains my SPSC queue implementation. The other two are from different authors, included just for benchmarking against.

The SPSC queue is composed of a circular linked list of blocks. `MAX_BLOCK_SIZE` is used to specify the maximum size of each block; when the queue grows dynamically, it adds a new block of no more than that size. For most applications (including a threadpool) the default of 512 is fine and you don't have to specify it explicitly.

**Comment by necromancersecret** [comment]
I am using your readwritequeue, now 
in my consumerthread i am doing something like this
Batchsize  = 20

while (!CThread::currentThread().isInterrupted()){
			int i = 0; 
			while (i < BatchSize){
				MsgObject tempObject; 
				if (m_QueueConsumer->try_dequeue(tempObject)){
					ptrDW->send(tempObject);
					i++;
				}
				if (i == BatchSize)
					ptrDW>doneSave();
			}

I have seen all the enqueue calls returned succee, then why m_QueueConsumer->try_dequeue, just start returning false after 5th of 6th iteration ?

**Comment by necromancersecret** [comment]
And another doubt please clarify that. I am writing very heavy app where there would be close to 100,000 + nodes getting inserted in a queue  at a second. 
queue->enqueue(o); where enqueue takes care of malloc/new depending upon the size of o, where o is object right ?.  
Hence N Producer thread, will have N Queues and each N Producer thread will insert close to 100000+ nodes and that keeps on growing . Will there will be any errors? 
Now when those nodes will gets deallocated , dequeue ?

**Comment by abhit011** [comment]
you this loop is wrong 
while (!CThread::currentThread().isInterrupted()){
int i = 0;
while (i < BatchSize){
MsgObject tempObject;
if (m_QueueConsumer->try_dequeue(tempObject)){
ptrDW->send(tempObject);
i++;
}
if (i == BatchSize)
ptrDW>doneSave();
}

**Comment by cameron314** [comment]
`try_dequeue` will fail if the consumer thread doesn't see the objects from the producer thread right away, or if the producer is producing slower than the consumer can process things.

Yes, the queue takes care of allocating memory. Note that even `enqueue` can fail if it needs to allocate more memory and malloc fails. 

Throughput doesn't affect the number of items in the queues at a given moment (which depends more on latency multiplied by throughput). If you can process 100000 items a second and the threads see new items every 100us, there will only be around 1000 items in each queue most of the time. 

Allocation works with blocks, so a whole block of slots is allocated at once. Once allocated, a block is never freed (until the queue is destroyed). But blocks are reused after their payload is completely dequeued, yes.

As for CPU usage, if you want to avoid spin waiting (which you might not need to avoid since you're working on a high throughput application), I suggest you use the blocking versions of the queue. Manually sleeping introduces unnecessary latency and is still less efficient than properly blocking. Also, minor nitpick: peeking followed by a try_dequeue is equivalent to just doing a try_dequeue, except less efficient.

**Comment by necromancersecret** [comment]
Is there any way we can maintain the order of the queue depending upon some unique ID, e.g queue gets inserted using a unique ID irrespective of the fact that it gets produced from various threads. And during dequeue operation , it maintains the order, is that thing is possible in any of your queue implementation ?
Neo

**Comment by cameron314** [comment]
Unfortunately not. You can of course generate your own monotonically-increasing IDs, but there's no guarantee which one will come out first (when multiple producers are involved).

If I were to redo the queue I'd implement it differently, since this seems to be a very common stumbling block. It turns out a lot of applications need that total order of elements. See enhancement #6.
