### ISSUE TITLE
static_assert failed "The queue does not support super-aligned types at this time" with T=std::function (iOS)

### ISSUE THREAD

**Issue by Tomcc** [cameron314/concurrentqueue#64]
I tried to use `ConcurrentQueue` in our project as a drop-in replacement of our crude `std::queue`+`std::mutex` queue, but unfortunately I've hit a snag on iOS.

When instantiating the queue with `std::function<void(void)>` that assertion in the title fails while building on Xcode7 for iOS, where it turns out that a lot of types have a bigger alignment than `max_align_t`:
- ```std::alignment_of <std::function<void()>>::value == 8``` 
- ```std::alignment_of <details::max_align_t>::value == 4```

I thought of opening this issue because I feel that the solution here might be more trivial than having to implement support for overaligned types. 
I'm not sure of how the `static_cast` could be fixed, but perhaps `max_align_t` isn't the right alignment to check there? 
I'm pretty sure that [`malloc`'s alignment on iOS is actually 16 bytes](https://developer.apple.com/library/content/documentation/Performance/Conceptual/ManagingMemory/Articles/MemoryAlloc.html), so the code should just work.

**Comment by cameron314** [comment]
Hmm, you're right, `max_align_t` provides a lower bound but `malloc` may align more than that. However, there's other places in the code that rely on `max_align_t` forcing the right alignment.

What does `alignof(double) and `alignof(uint64_t)` return on iOS? Surely these have a natural alignment requirement of 8 bytes?

**Comment by Tomcc** [comment]
@cameron314 as expected both `alignof(double)` and `alignof(uint64_t)` is 8, so that's weird.

**Comment by cameron314** [comment]
Seems like a bug in the standard library headers, then. `max_align_t` [is supposed to be aligned at least as much as every scalar type](http://en.cppreference.com/w/cpp/types/max_align_t).

I'll have to work around this with a custom max_align_t that includes a `long double` in a union.

**Comment by cameron314** [comment]
Try now?

**Comment by Tomcc** [comment]
Wow, super fast, thanks :)
I'm actually flying out tomorrow and I didn't actually expect a reply so soon or at all, I'll try to find some time ASAP!
However it looks like it would work, I'll also let you know if QA finds crashes. There's always the option that `max_align_t` was 4 for a reason, which would probably lead to very obscure crashes.

**Comment by Tomcc** [comment]
I'm back!
I'm puzzled, because the error still fires.
```static_assert failed "The queue does not support super-aligned types at this time"
static_assert(std::alignment_of<T>::value <= std::alignment_of<details::max_align_t>::value, "The queue does not support super-aligned types at this time");
 note: in instantiation of member class 'moodycamel::ConcurrentQueue<std::__1::function<void ()>, moodycamel::ConcurrentQueueDefaultTraits>::Block' requested here
public integral_constant<size_t, __alignof__(_Tp)> {};
```

However ```static_assert(std::alignment_of<std::function<void(void)>::value == 8, "function is 8 bytes");```
does *not* fail, so I'm not really sure of what's going on now.

PS: another small issue is that when building on iOS and OSX with `-fno-exceptions`, the build fails because `MOODYCAMEL_EXCEPTIONS_ENABLED` is set anyway. The proper macro to test if you're able to use `throw/try/catch` seems to be `__cpp_exceptions`.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64276

```__EXCEPTIONS is ambiguous; it can mean either "generate cleanups on exception unwind paths" or "allow C++ exception handling syntax", and some compilers allow these flags to be set independently. It would be more portable (and would set a better example) to use __cpp_exceptions and __cpp_rtti rather than these macros, now that GCC supports them.```

**Comment by cameron314** [comment]
Gah, thanks. I don't have an iOS device to test any of this on, so there's some turnaround if I don't get things right the first time ;-)

The natural alignment of the `max_align_t` union *must* be at least equal to the maximum alignment of its members. This is somewhere in the C++ standard. Without this, it's impossible to use the union's members safely.

Out of curiosity, if you move the `#include` for concurrentqueue.h to the very top of your translation unit, does the `static_assert` still fire? (This would rule out a dangling alignment `#pragma` somewhere.)

I wasn't aware of `__cpp_exceptions`, I'll fix that shortly, thanks!

**Comment by Tomcc** [comment]
Back to work! I'll test the alignment of `max_align_t` on iOS, also the `#include` is already at the top of the translation unit, in fact it's at the top of the precompiled header.
I had to do this already because `windows.h` seems to define the macro `U` which breaks all the template arguments.

**Comment by cameron314** [comment]
Sorry for the delay. Hmm. Well, in that case, technically `std::function` really is a super-aligned type on your platform, and the queue doesn't support it because there's no easy way to force the alignment of its internal `Block` structure to be the same as the alignment of the contained type (`alignas` isn't enough with dynamic memory allocation).

Perhaps use a different type? Would a raw function pointer work? How about a `std::unique_ptr<std::function<void, void>>`?

**Comment by Tomcc** [comment]
Hmm just to understand better - what does the requirement for alignment come from? 
As I said, `malloc` is aligned to 16 bytes minimum on iOS, so although `std::function`, `double`, `int64_t` etc are technically super-aligned, they will never be misaligned when allocated dynamically.
I think this means that the queue is indeed safe to use on iOS?

Otherwise, I can't really use this in the project other than specific places - wrapping things in the heap is a solution, but that means I can't just drop this where we use `std::mutex`+`std::queue`, which sucks :(

**Comment by cameron314** [comment]
Let's see if I can explain more clearly :-)

`double` and `int64_t` are not super-aligned on your platform; they require only a 4-byte alignment despite taking up more space than that. `std::function`, however, appears to actually have an alignment requirement of 8 bytes (for whatever reason). This is a problem because I can't force the alignment of the internal `Block` structure to 8 without jumping through significant hoops.

Yes, `malloc` will almost certainly return memory aligned to 16 bytes. But this doesn't help unless each individual `std::function` element is allocated individually, which it isn't. A fair amount of the queue's speed arises from using fixed-size arrays of elements (this is what a `Block` encapsulates) instead of allocating each one dynamically one at a time. So if I allocate a block which contains an array of `std::function` and some other stuff, the first one will be aligned (because of `malloc`'s over-alignment) but there's no guarantee that the 2nd, 3rd, etc. will be aligned (and they generally aren't).

Is there really a measurable difference in using a lock-free queue over `std::mutex` + `std::queue` when dealing with functors (which tend to have non-negligible overhead)? Note also that this queue is not a drop-in replacement for a mutex-protected queue anyway because it provides none of the same guarantees about linearizability (e.g. there is no inherent ordering between elements enqueued on different threads).

**Comment by Tomcc** [comment]
Got it, thanks for the explanation! We could still take the speed hit on iOS though, as long as it's actually not incorrect.
If the only problem is speed, I'll run some benchmarks and confirm if ARMv7 has a problem with this or not... 

In fact, running a iOS64 (where the queue works as intended) vs iOS32 (where the queue is superaligned) vs std::mutex+std::queue would be interesting to see if this is worth it.

re drop in replacement: The std::mutex + std::queue have been wrapped already in a `MPMCQueue` class that has the same semantics as yours, and was always intended to be replaced with a lockless one eventually - meaning that despite it has inherent ordering, users aren't supposed to rely on that.
So it is a drop-in because we already used the previous queue as a channel between threads.
I assume that perf is going to be better, but the main reason for this is that often the consumer or producer is the rendering thread, and waits/locks on the main thread are a Bad Thing; switching to this should guarantee that the main thread doesn't skip a frame for being unlucky when using the queue.

**Comment by cameron314** [comment]
Cool. Benchmarks are always good :-)
I'm impressed by your foresight re relaxed lock-free ordering guarantees! It's easy to accidentally assume a global total order just because it's generally always the case in normal (non-lock-free) code.

I'm curious now as to why the alignment of `std::function` is always 8 bytes -- is there something that inherently requires that alignment? What happens if you create an array of such types on 32-bit iOS with compiler diagnostics turned up -- is there a compiler warning about the alignment not being respected? Or is there enough padding inserted that `std::function` is always a multiple of 8 bytes?

Anyway, I'm hesitant to just suggest removing the `static_assert` since even if it seems to work, it's possible that a compiler optimization will kick in one day that relies on the alignment (for reference, this has actually happened with my queue -- someone reported clang generating AVX instructions on data that turned out to be misaligned at runtime, causing a crash -- which led to my inserting that `static_assert` in the first place after fixing the problem).

**Comment by Tomcc** [comment]
Well I didn't say that nobody accidentally required global total order, but given the use cases (eg. collecting events on a few threads and doing something on a consumer), it's likely nobody did :P
That's another thing we'll have to test for, but it's intended - if someone wants those stronger guarantees they should explicitly use a mutex. I believe that blocking should be explicitly handled because it's expensive, and generally a last-resort option. Most of the time you can just rethink the algorithm to make it work with weaker (eg. faster) guarantees and no locks.

re: the function: I don't really know without looking at their source, it seems that it has to be manually aligned, too. I'll have to check better once I'm on a Mac. 

Anyway, I'll consider if we should use this (and remove the assert on old iOS) or not... It definitely feels risky to just remove that, and it could be a really tough crash to reproduce before shipping.
Thanks a lot for the help, it's been pretty educative although there wasn't really anything to solve after all :P

**Comment by WillerZ** [comment]
`alignof(long long int)` is > `alignof(long double)` on iOS 32-bit. The minimum portable workaround (presuming all other platforms are correct) is a union containing a `long long` and an `std::max_align_t`

**Comment by cameron314** [comment]
Hmm, interesting! I'm assuming this means `malloc` returns memory aligned to at least 8 bytes.

Good find, thanks! I'll try to integrate this soon.

**Comment by cameron314** [comment]
Try now?

**Comment by Tomcc** [comment]
That's been a really long time, I appreciate you're still looking into this!
It's funny because I'm just about to revive the work that needed `concurrentqueue`, so I should be able to let you know "soonish" if it works or not!

**Comment by pradeep250677** [comment]
Is this issue fixed ?

**Comment by cameron314** [comment]
I don't know, nobody ever got back to me :-)

**Comment by cameron314** [comment]
No worries. It'd be nice to be able to close the issue, but don't go out of your way.

**Comment by lcfb91** [comment]
I have tested here and is not yet solved. 
Apparently is only iOS-32 bit which minimizes the problem, but this issue affects all iphones released before iPhone 5s.
Here is the log, let me know if I can help someway. It is easy for me to test a new version.
Thanks
`
include/moodycamel/concurrentqueue.h:2962:24: error: no member named 'dynamicallyAllocated' in 'moodycamel::ConcurrentQueue<std::__1::pair<std::__1::function<bool ()>, std::__1::function<void ()> >, moodycamel::ConcurrentQueueDefaultTraits>::Block'
                        initialBlockPool[i].dynamicallyAllocated = false;
                        ~~~~~~~~~~~~~~~~~~~ ^
include/moodycamel/concurrentqueue.h:738:3: note: in instantiation of member function 'moodycamel::ConcurrentQueue<std::__1::pair<std::__1::function<bool ()>, std::__1::function<void ()> >, moodycamel::ConcurrentQueueDefaultTraits>::populate_initial_block_list' requested here
                populate_initial_block_list(capacity / BLOCK_SIZE + ((capacity & (BLOCK_SIZE - 1)) == 0 ? 0 : 1));
                ^
include/moodycamel/blockingconcurrentqueue.h:455:5: note: in instantiation of member function 'moodycamel::ConcurrentQueue<std::__1::pair<std::__1::function<bool ()>, std::__1::function<void ()> >, moodycamel::ConcurrentQueueDefaultTraits>::ConcurrentQueue' requested here
                : inner(capacity), sema(create<LightweightSemaphore>(), &BlockingConcurrentQueue::template destroy<LightweightSemaphore>)
                  ^
include/commons/util/wrappers/SBQueue.h:27:5: note: in instantiation of member function 'moodycamel::BlockingConcurrentQueue<std::__1::pair<std::__1::function<bool ()>, std::__1::function<void ()> >, moodycamel::ConcurrentQueueDefaultTraits>::BlockingConcurrentQueue' requested here
    SBQueue();
    ^
include/commons/util/functions/AsyncParallelDispatcher.h:14:14: note: in instantiation of member function 'SBQueue<std::__1::pair<std::__1::function<bool ()>, std::__1::function<void ()> > >::SBQueue' requested here
    explicit AsyncParallelDispatcher(bolina::types::Int number_of_threads = 1) : _number_of_threads(number_of_threads) {
`

**Comment by cameron314** [comment]
Hmm. That looks like a completely different problem! :-)
The member `dynamicallyAllocated` is quite clearly there in the `Block` type, and it's even `public`.

Are there any other errors or warnings?

**Comment by lcfb91** [comment]
[log.txt](https://github.com/cameron314/concurrentqueue/files/2562536/log.txt)
Sorry, the full log is attached. Is the same error but I cut some (wrong) lines :p

**Comment by cameron314** [comment]
Alright, that makes more sense. The `static_assert` is causing the structure to stop being parsed, leading to the other cascading errors.

If it's not too much trouble, can you extract the following values on iOS 32-bit:

    printf("long long: %d\n, alignof(long long));
    printf("double: %d\n, alignof(double));
    printf("long double: %d\n, alignof(long double));
    printf("max_align_t: %d\n, alignof(max_align_t));
    printf("std::function<bool()>: %d\n, alignof(std::function<bool()>));
    printf("std::function<void()>: %d\n, alignof(std::function<void()>));
    printf("std::pair<int, int>: %d\n, alignof(std::pair<int, int>));
    printf("std::pair<std::function<bool()>, std::function<void()>>: %d\n, alignof(std::pair<std::function<bool()>, std::function<void()>>));

**Comment by lcfb91** [comment]
arch-> x86 ||is 64bit?? NO
long long: 8
double: 8
long double: 16
max_align_t: 16
std::function<bool()>: 8
std::function<void()>: 8
std::pair<int, int>: 4
std::pair<std::function<bool()>, std::function<void()>>: 8


arch-> x86 ||is 64bit?? YES
long long: 8
double: 8
long double: 16
max_align_t: 16
std::function<bool()>: 16
std::function<void()>: 16
std::pair<int, int>: 4
std::pair<std::function<bool()>, std::function<void()>>: 16

**Comment by cameron314** [comment]
Thanks! 

Hmm, that's odd. Both sets of output show the alignment of max_align_t is at least as large as the alignment of the element types, so the `static_assert` should not happen.

Maybe `std::alignment_of<...>::value` returns different values than `alignof`?

**Comment by Tomcc** [comment]
That is a bit odd also because when I checked for [this post here](https://github.com/cameron314/concurrentqueue/issues/64#issuecomment-271294937) the alignment of almost everything (including long long and double) was 4 🤔

**Comment by cameron314** [comment]
@lcfb91 Are you sure this was on iOS 32-bit? The output, particularly "arch-> x86", doesn't quite seem to match what we've been seeing...

**Comment by GHScan** [comment]
After some investigation, I can explain something discussed above : 

1. There's a member declared as 'std::aligned_storage<3 * sizeof(void*)>' in std::function
2. alignof(std::aligned_storage<3 * sizeof(void*)>) would be 8
3. The aligned_storage is implemented as:
    ```template <size_t _Len, size_t _Align = std::__find_max_align<std::__all_types, _Len>::value>
    struct aligned_storage
    {
        typedef typename std::__find_pod<std::__all_types, _Align>::type _Aligner;
        static_assert(!std::is_void<_Aligner>::value, "");
        union type
        {
            _Aligner __align;
            unsigned char __data[(_Len + _Align - 1)/_Align * _Align];
        };
    };
   ```
   Where _Aligner would be 'unsigned long long' if _Len = 12
4. Although the aligned_storage works fine, the following would have a alignment 4:
    ```
    struct Test {
    int i;
    long long j;
    unsigned long long k;  // alignof(unsigned long long) == 8
   };
    ```
   Another article provided by Apple discussed the same thing: [Review your app's data design and update it to conform with 64-bit architecture](https://developer.apple.com/documentation/uikit/app_and_environment/updating_your_app_from_32-bit_to_64-bit_architecture/updating_data_structures). 
   One more thing, if I move above std::aligned_storage difinition into the main function written by myself, it's alignment would be 4 instead of 8

It seems the C++ function alignof/alignment_of cannot work consistently on 32-bit iOS. For 64-bit interger, they may return 4 or 8 in different context. Although it is legal to make the size/alignment different for primitive types, but this context sensitive behavior is not compilant to C++ Standard.

**Comment by cameron314** [comment]
I'm going to close this for now. If anyone has a workaround, please let me know.

**Comment by cameron314** [comment]
Super-aligned types are now supported in any case. See pull request #84.
