### ISSUE TITLE
how can i get the size of the queue?

### ISSUE THREAD

**Issue by owen200008** [cameron314/concurrentqueue#66]
whether i can get the size of the queue or know is empty or not?

**Comment by cameron314** [comment]
You can use the `size_approx()` method to determine the approximate size of the queue, but you can't get the exact size. The queue is non-linearizable, which basically means operations overlap and, since memory effects can take a while to propagate to other cores/threads (with multiple operations in parallel compounding things), there is no clear-cut state change from 'empty' to 'non-empty' and vice versa. It's a trade-off for improved performance.

**Comment by owen200008** [comment]
thanks it is enough, when i see the code i miss the function.
