### ISSUE TITLE
Can we use this library in production?

### ISSUE THREAD

**Issue by zieckey** [cameron314/concurrentqueue#77]
Do you suggest to use the master branch or the release version `v1.0.0-beta`?
Thanks.

**Comment by cameron314** [comment]
The master branch contains bug fixes that aren't in the first release, and I try to keep it stable. I would suggest using the master.

I would proceed with caution if using this in production, though, since despite the effort I put into testing, there still seems to be issues for some people that I haven't been able to investigate fully yet.

Is it stable and of good quality? Yes, I think so. I would use it in commercial software (e.g. games, desktop applications, webapp backends...). Is it rock-solid enough to use in scenarios where significant amounts of money and/or people's lives are in the balance? No, absolutely not. It hasn't been around long enough for that kind of maturity to evolve. I'm the only significant contributor, and that means there's not been nearly enough eyeballs on it for that level of certainty to emerge.

**Comment by zieckey** [comment]
Got it. That's great. I will try it in our webapp backends.
Thank you very much.
