### ISSUE TITLE
Request: try_discard_front

### ISSUE THREAD

**Issue by martinfinke** [cameron314/concurrentqueue#94]
Would it be possible to add a member function like `bool try_discard_front()`? It's like `try_dequeue`, but it just throws the queue's first item away. And therefore, does not need a parameter of type `T&`. It could return `true` if an item was dropped, but for my purposes, it could also just return `void`.

The use case is: I have a class template (let's call it `MyQueue<T>`) that has a `ConcurrentQueue<T>` member. If another item should be enqueued and the queue is full, my class drops the first item from the queue, until there's space:

```cpp
while (!queue.try_enqueue(newItem))
    queue.try_dequeue(unusedDummy);
```

The question is: Where do I put a `T unusedDummy`? If I create it locally, I have to default-construct it every time, without actually needing it. If I hold it as a member variable, then enqueueing items from multiple producers is a data race on that variable. And if it's not default-constructible, the user has to tell `MyQueue` how to create an instance of `T`.

Would it be possible to add this feature? :)

**Comment by martinfinke** [comment]
I've just found another problem with this. Sometimes, the code above seems to run endlessly. Both `try_enqueue` and `try_dequeue` return `false` all the time.
Do you know why this may be happening? It's the same when using `try_dequeue_bulk` instead (it returns `0`).

**Comment by cameron314** [comment]
Really sorry for the lack of response, I've been neglecting my open source projects as of late.

The short answer is that I'm not going to add this method.

Your use case is perfectly valid, but as you've discovered, the loop that removes elements to "make room" for more elements is less than ideal due to the internal design of the queue; since the queue is implemented using sub-queues of blocks of elements (and not just a simple ring-buffer of elements), dropping the first item only rarely frees up space for another item to be enqueued. Generally, an entire block's worth of elements would have to be discarded in order to make room for another element (though subsequent elements would also have room in the fresh block).

Now, as to why the loop can be infinite, even if the queue is completely emptied: `try_enqueue` is guaranteed not to allocate memory, for any reason. This means that even if the queue is completely drained and all the blocks are ready to be reused, the hash table of implicit producers may be full (see `Traits::INITIAL_IMPLICIT_PRODUCER_HASH_SIZE`), but it can't be resized without allocating memory. To see if this is the case, try bumping the trait to an absurdly high power of 2 (e.g. 64*1024) and see if you can reproduce.

I think in your case it might make more sense to use a simple lock-free ring-buffer, which generally have a mode where you can overwrite the least recent element when the buffer is full.

**Comment by martinfinke** [comment]
Thanks for the reply! I'm currently working around it by using a producer token, since I'm only calling the above while-loop from one thread anyway. So what you wrote about the hash table of implicit producers is probably the case. I can't test it extensively right now, though.
